name: Bandit Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: |
        bandit -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.json

    - name: Fail on High Severity
      run: |
        bandit -r . --severity-level high