name: Multi-Project Security Scan

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  scan-student_management_system:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Bandit
      run: pip install bandit

    # Vulnerable app scan
    - name: Scan student_management_system
      id: vulnerable_scan
      continue-on-error: true
      run: |
        bandit -r student_management_system \
        -f json \
        -o student_management_system-report.json

    # Upload report EVEN IF scan failed
    - name: Upload student_management_system Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: student_management_system-bandit-report
        path: student_management_system-report.json

    # Explicitly fail workflow if vulnerabilities exist
    - name: Fail Workflow for Vulnerable App
      if: steps.vulnerable_scan.outcome == 'failure'
      run: |
        echo "High severity vulnerabilities detected!"
        exit 1


  scan-patch_student_management_system:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Bandit
      run: pip install bandit

    # Patched app scan
    - name: Scan patch_student_management_system
      run: |
        bandit -r patch_student_management_system \
        -f json \
        -o patch_student_management_system-report.json

    # Upload report
    - name: Upload patch_student_management_system Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: patch_student_management_system-bandit-report
        path: patch_student_management_system-report.json